version: '3.6'

services:

  go-censor-svc:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/GoCensor-service
    restart: on-failure
    environment:
      DEBUG: ${DEBUG}
    extra_hosts:
      - host.docker.internal:host-gateway
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - main

networks:
  main:
    external: true